name: alan_assistant
description: Alan V1 Flutter UI
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management
  provider: ^6.1.0

  # Networking
  dio: ^5.3.2

  # LiveKit real-time
  livekit_client: ^2.3.0

  # Storage
  shared_preferences: ^2.2.2

  # UUID for chat session
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/alan_avatar.png
