name: alan_assistant
description: Alan Assistant UI
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  http: ^1.2.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  livekit_client: ^2.3.6
  dio: ^5.4.0

flutter:
  uses-material-design: true
